# Generated by Django 3.1.2 on 2020-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='answer',
            field=models.TextField(blank=True, verbose_name='answer'),
        ),
    ]
