# Generated by Django 3.1.2 on 2020-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201008_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(blank=True, choices=[('FIRST', 'First Choice'), ('SECOND', 'Second Choice'), ('THIRD', 'Third Choice'), ('FOURTH', 'Fourth Choice')], max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'Answer is text'), ('CHOICE', 'Answer is choice'), ('VALUE', 'Answer is value')], default='TEXT', max_length=256),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
    ]
