# Generated by Django 3.1.2 on 2020-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20201009_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(verbose_name='question_id')),
                ('answer', models.CharField(choices=[('FIRST', 'First Choice'), ('SECOND', 'Second Choice'), ('THIRD', 'Third Choice'), ('FOURTH', 'Fourth Choice')], max_length=256, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(verbose_name='question_id')),
                ('answer', models.TextField(verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(verbose_name='question_id')),
                ('answer', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='answer')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
