# Generated by Django 3.1.1 on 2020-10-04 20:39

# DB structure:
# 1. Users: user_id, username, email, password_hash, role
# 2. Courses: course_id, course_name, professor_id (==user_id), groups_ids[]
# 3. Groups: group_id, course_id, group_name, students[] (==user_id[])

# 4. Feedbacks: feedback_id, group_id, data(, answered_users[])
# 5. Answers: answer_id, feedback_id, data

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
	migrations.RunSQL([
			"CREATE TABLE IF NOT EXISTS users ("
			+ "user_id serial UNIQUE, "
			+ "username varchar(40) NOT NULL, " # username and email no more than 40 characters
			+ "email varchar(40) NOT NULL, "
			+ "password_hash varchar(32) NOT NULL, " # md5 password hash
			+ "role varchar(20))", # I believe that it'll be enough for the field

			"CREATE TABLE IF NOT EXISTS courses ("
			+ "course_id serial UNIQUE, "
			+ "course_name TEXT, "
			+ "professor_id INT, "
			+ "group_ids INT[])",

			"CREATE TABLE IF NOT EXISTS groups ("
			+ "group_id serial UNIQUE, "
			+ "course_id INT NOT NULL, "
			+ "group_name varchar(20), "
			+ "student_ids INT[])",

			"CREATE TABLE IF NOT EXISTS feedbacks ("
			+ "feedback_id serial UNIQUE, "
			+ "group_id INT NOT NULL, "
			+ "data TEXT)",

			"CREATE TABLE IF NOT EXISTS answers ("
			+ "answer_id serial UNIQUE, "
			+ "feedback_id INT NOT NULL, "
			+ "data TEXT)"
		])
    ]
