# Generated by Django 2.0.13 on 2020-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student of a Uni'), ('professor', 'professor of a Uni')], max_length=20),
        ),
    ]
