# Generated by Django 3.1.1 on 2020-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin of the service'), ('student', 'student of a Uni'), ('professor', 'professor of a Uni')], max_length=20),
        ),
    ]
