# Generated by Django 2.0.13 on 2020-10-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('group_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='feedback_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Feedback'),
        ),
    ]
