# Generated by Django 3.1.1 on 2020-10-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201011_1939'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='group_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.group'),
        ),
    ]
